version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 147997146302.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t cryptochain .
      - docker tag cryptochain:latest 147997146302.dkr.ecr.us-east-1.amazonaws.com/cryptochain:latest
  post_build:
    commands:
      - docker push 147997146302.dkr.ecr.us-east-1.amazonaws.com/cryptochain:latest
      - echo Writing image definitions file...
      - printf '[{"name":"mywebsite","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
